server:
  port: 55555
#  context-path: /

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hrsys?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
      username: root
      password: 123456

jwt:
  secret-key: hrsys
  ttl: 7200000  # 1000*60*60*2
  token-name: token